
name: Python Build and Test

on:
  push:
    branches:
      - master  # or 'main', depending on your default branch
  pull_request:
    branches:
      - master  # or 'main', depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python_project/requirements.txt

      - name: Run Python script
        run: python python_project/main.py
